import type { Locale } from "@/types/portfolio";
import type { LabPlaceholderCard } from "@/types/lab";

/**
 * Placeholders del bento para previsualizar el índice lleno
 * (11 slots de contenido + hero = 12). No son MDX ni rutas publicables.
 */
const PLACEHOLDERS: Record<Locale, LabPlaceholderCard[]> = {
  es: [
    {
      id: "ph-guia-ifc",
      type: "guia",
      size: "md",
      title: "Exportar IFC limpio desde Revit",
      description: "Checklist visual de qué limpiar antes de compartir el modelo.",
      tags: ["IFC", "Revit", "BIM"],
      tone: "teal",
    },
    {
      id: "ph-checklist-qa",
      type: "checklist",
      size: "sm",
      title: "QA BIM en 15 minutos",
      description: "Una pasada rápida de calidad antes de entregar.",
      tags: ["QA", "BIM"],
      tone: "amber",
    },
    {
      id: "ph-nota-prompts",
      type: "nota",
      size: "sm",
      title: "5 prompts útiles para modelado",
      description: "Plantillas cortas para pedir ayuda a la IA sin rodeos.",
      tags: ["IA", "Prompts"],
      tone: "violet",
    },
    {
      id: "ph-infografia-mcp",
      type: "infografia",
      size: "wide",
      title: "Mapa visual del protocolo MCP",
      description: "De Cursor a Revit: quién habla con quién y por qué.",
      tags: ["MCP", "Cursor", "Revit"],
      tone: "sky",
    },
    {
      id: "ph-dashboard-kpi",
      type: "dashboard",
      size: "md",
      title: "KPIs de coordinación en obra",
      description: "Qué mirar cada semana sin ahogarte en Excel.",
      tags: ["KPI", "Obra"],
      tone: "coral",
    },
    {
      id: "ph-tutorial-dynamo",
      type: "tutorial",
      size: "lg",
      title: "Automatiza planos con Dynamo + IA",
      description: "De la idea al script: pasos claros para quien empieza.",
      tags: ["Dynamo", "IA", "Revit"],
      tone: "indigo",
    },
    {
      id: "ph-guia-navis",
      type: "guia",
      size: "md",
      title: "Clash detection sin drama",
      description: "Cómo preparar el modelo antes de abrir Navisworks.",
      tags: ["Navisworks", "Clash"],
      tone: "olive",
    },
    {
      id: "ph-checklist-entrega",
      type: "checklist",
      size: "sm",
      title: "Entrega digital al cliente",
      description: "Lo mínimo que debe salir del BIM Manager.",
      tags: ["Entrega", "CDE"],
      tone: "rose",
    },
    {
      id: "ph-nota-python",
      type: "nota",
      size: "sm",
      title: "Python en Revit sin miedo",
      description: "Tres conceptos para leer un script de pyRevit.",
      tags: ["Python", "pyRevit"],
      tone: "mint",
    },
    {
      id: "ph-dashboard-coste",
      type: "dashboard",
      size: "md",
      title: "Coste vs avance en tiempo real",
      description: "Una vista simple para reunión de obra.",
      tags: ["Coste", "4D"],
      tone: "slate",
    },
  ],
  en: [
    {
      id: "ph-guia-ifc",
      type: "guia",
      size: "md",
      title: "Export a clean IFC from Revit",
      description: "A visual checklist of what to clean before sharing the model.",
      tags: ["IFC", "Revit", "BIM"],
      tone: "teal",
    },
    {
      id: "ph-checklist-qa",
      type: "checklist",
      size: "sm",
      title: "BIM QA in 15 minutes",
      description: "A fast quality pass before you hand over.",
      tags: ["QA", "BIM"],
      tone: "amber",
    },
    {
      id: "ph-nota-prompts",
      type: "nota",
      size: "sm",
      title: "5 useful modeling prompts",
      description: "Short templates to ask AI for help without fluff.",
      tags: ["AI", "Prompts"],
      tone: "violet",
    },
    {
      id: "ph-infografia-mcp",
      type: "infografia",
      size: "wide",
      title: "Visual map of the MCP protocol",
      description: "From Cursor to Revit: who talks to whom and why.",
      tags: ["MCP", "Cursor", "Revit"],
      tone: "sky",
    },
    {
      id: "ph-dashboard-kpi",
      type: "dashboard",
      size: "md",
      title: "Site coordination KPIs",
      description: "What to watch every week without drowning in spreadsheets.",
      tags: ["KPI", "Site"],
      tone: "coral",
    },
    {
      id: "ph-tutorial-dynamo",
      type: "tutorial",
      size: "lg",
      title: "Automate sheets with Dynamo + AI",
      description: "From idea to script: clear steps for beginners.",
      tags: ["Dynamo", "AI", "Revit"],
      tone: "indigo",
    },
    {
      id: "ph-guia-navis",
      type: "guia",
      size: "md",
      title: "Clash detection without the drama",
      description: "How to prep the model before opening Navisworks.",
      tags: ["Navisworks", "Clash"],
      tone: "olive",
    },
    {
      id: "ph-checklist-entrega",
      type: "checklist",
      size: "sm",
      title: "Digital handover to the client",
      description: "The minimum a BIM Manager should ship.",
      tags: ["Handover", "CDE"],
      tone: "rose",
    },
    {
      id: "ph-nota-python",
      type: "nota",
      size: "sm",
      title: "Python in Revit without fear",
      description: "Three concepts to read a pyRevit script.",
      tags: ["Python", "pyRevit"],
      tone: "mint",
    },
    {
      id: "ph-dashboard-coste",
      type: "dashboard",
      size: "md",
      title: "Cost vs progress in real time",
      description: "A simple view for the site meeting.",
      tags: ["Cost", "4D"],
      tone: "slate",
    },
  ],
};

export function getLabPlaceholders(locale: Locale): LabPlaceholderCard[] {
  return PLACEHOLDERS[locale];
}
